//! Finalidad de las herramientas del catálogo.
//!
//! Este módulo no sabe cómo se instala nada. Esa separación es deliberada:
//! una descripción debe ayudar a decidir si el programa sirve para el trabajo
//! del usuario; requisitos, permisos, repositorios y avisos pertenecen a
//! `InstallAction::hint`.

fn without_lifecycle_suffix(mut id: &str) -> &str {
    loop {
        let previous = id;
        for suffix in [
            "-uninstall",
            "-update",
            "-version",
            "-remove",
            "-check",
            "-open",
        ] {
            if let Some(base) = id.strip_suffix(suffix) {
                id = base;
                break;
            }
        }
        if id == previous {
            return id;
        }
    }
}

/// Texto breve, específico y estable para la finalidad de una herramienta.
/// Los alias de Windows y Linux comparten descripción para que las dos builds
/// presenten el mismo producto aunque cambie el instalador.
pub(super) fn action_description(id: &str) -> Option<&'static str> {
    let id = without_lifecycle_suffix(id);
    if let Some(tool) = id.strip_prefix("brew-") {
        return action_description(&format!("pkg-{tool}"));
    }
    let description = match id {
        "winget-pwsh" | "pkg-pwsh" => "Shell moderna de Microsoft para automatización y administración multiplataforma.",
        "winget-nushell" | "pkg-nushell" => "Shell estructurada que trata la salida de los comandos como tablas y datos.",
        "pkg-bash" => "Shell POSIX ampliamente usada para scripts y administración de sistemas.",
        "pkg-zsh" => "Shell interactiva compatible con muchos scripts de sh y muy extensible.",
        "pkg-fish" => "Shell interactiva con sugerencias, completado y configuración sencilla.",
        "pkg-xonsh" => "Shell que combina comandos del sistema con expresiones y scripts de Python.",
        "pkg-elvish" => "Shell expresiva con datos estructurados, canalizaciones y lenguaje propio.",
        "sh" => "Intérprete POSIX básico para ejecutar scripts portables del sistema.",
        "winget-git" | "pkg-git" => "Control de versiones distribuido para código, ramas y colaboración.",
        "winget-git-lfs" | "pkg-git-lfs" => "Extensión de Git que almacena archivos grandes sin inflar el historial del repositorio.",
        "winget-gh" | "pkg-gh" => "Cliente oficial para repositorios, incidencias, pull requests y Actions de GitHub.",
        "winget-wt" => "Emulador de terminal de Windows con pestañas, perfiles y aceleración gráfica.",
        "winget-ripgrep" | "pkg-ripgrep" => "Búsqueda de texto recursiva muy rápida que respeta las reglas de Git.",
        "winget-fd" | "pkg-fd" => "Buscador de archivos rápido con sintaxis sencilla y exclusiones de Git.",
        "winget-fzf" | "pkg-fzf" => "Selector difuso interactivo para filtrar archivos, historial y cualquier lista.",
        "winget-bat" | "pkg-bat" => "Visor de texto con resaltado, números de línea e integración con Git.",
        "winget-eza" | "pkg-eza" => "Listado de archivos moderno con colores, metadatos, árbol e información de Git.",
        "winget-just" | "pkg-just" => "Ejecutor de recetas de proyecto más simple y legible que un Makefile general.",
        "winget-terraform" => "Define y aplica infraestructura reproducible mediante archivos declarativos.",
        "winget-opentofu" => "Alternativa abierta para gestionar infraestructura declarativa compatible con Terraform.",
        "winget-aws-cli" => "Cliente oficial para administrar recursos y automatizaciones de Amazon Web Services.",
        "winget-azure-cli" => "Cliente oficial para crear y administrar recursos de Microsoft Azure.",
        "winget-jq" | "pkg-jq" => "Consulta, filtra y transforma documentos JSON desde la línea de comandos.",
        "winget-yq" | "pkg-yq" => "Consulta y modifica YAML, JSON y XML desde scripts y canalizaciones.",
        "choco-nsudo" => "Ejecuta procesos con distintos niveles de elevación para diagnóstico avanzado de Windows.",

        "winget-node" | "pkg-node" => "Runtime de JavaScript del lado del servidor con el gestor de paquetes npm.",
        "tool-typescript" | "pkg-typescript" => "Añade tipos estáticos a JavaScript y permite ejecutar TypeScript durante el desarrollo.",
        "winget-autohotkey" => "Lenguaje de automatización para atajos, macros, ventanas y tareas de escritorio en Windows.",
        "winget-haxe" | "pkg-haxe" => "Lenguaje multiplataforma que compila a JavaScript, C++, Java, C# y otros destinos.",
        "winget-octave" | "pkg-octave" => "Entorno numérico compatible con gran parte del lenguaje de MATLAB.",
        "winget-maxima" | "pkg-maxima" => "Sistema de álgebra computacional para cálculo simbólico y matemáticas exactas.",
        "winget-racket" | "pkg-racket" => "Lenguaje de la familia Lisp orientado a crear lenguajes, enseñar y desarrollar aplicaciones.",
        "winget-sbcl" | "pkg-sbcl" => "Implementación rápida y madura de Common Lisp con compilador nativo.",
        "winget-swipl" | "pkg-swipl" => "Implementación de Prolog para lógica, reglas, restricciones y conocimiento simbólico.",
        "pkg-guile" => "Implementación de Scheme diseñada para incrustar y extender aplicaciones.",
        "pkg-tcl" => "Lenguaje dinámico compacto usado en automatización, pruebas e interfaces Tk.",
        "pkg-gforth" => "Implementación portable de Forth para programación interactiva y de bajo nivel.",
        "winget-zig" | "pkg-zig" => "Lenguaje de sistemas con compilación cruzada integrada e interoperabilidad con C.",
        "winget-swift" | "pkg-swift" => "Lenguaje compilado de Apple para aplicaciones, servidores y herramientas.",
        "winget-python" | "pkg-python" => "Lenguaje generalista para automatización, web, datos, ciencia y herramientas.",
        "pkg-python-pip" => "Gestor de paquetes de Python para instalar bibliotecas y herramientas del ecosistema.",
        "winget-ruby" | "pkg-ruby" => "Lenguaje dinámico centrado en legibilidad, scripting y aplicaciones web.",
        "winget-java" | "pkg-java" => "Kit de desarrollo Java con compilador, runtime, herramientas y REPL jshell.",
        "winget-php" | "pkg-php" => "Lenguaje y runtime ampliamente usado para aplicaciones y servicios web.",
        "winget-go" | "pkg-go" => "Lenguaje compilado para servicios, redes y herramientas concurrentes.",
        "winget-rust" | "pkg-rust" => "Lenguaje de sistemas con seguridad de memoria y gestor de paquetes Cargo.",
        "winget-perl" | "pkg-perl" => "Lenguaje maduro para texto, automatización y administración de sistemas.",
        "winget-lua" | "pkg-lua" => "Lenguaje pequeño y rápido pensado para scripting e integración en aplicaciones.",
        "winget-deno" | "pkg-deno" => "Runtime seguro para JavaScript y TypeScript con herramientas integradas.",
        "winget-bun" | "pkg-bun" => "Runtime y conjunto de herramientas JavaScript con gestor, bundler y test runner.",
        "winget-julia" | "pkg-julia" => "Lenguaje de alto rendimiento para cálculo científico, datos y modelado numérico.",
        "winget-r" | "pkg-r" => "Lenguaje y entorno para estadística, análisis de datos y visualización.",
        "winget-dotnet" | "pkg-dotnet-sdk" => "SDK para crear, probar y publicar aplicaciones .NET en C#, F# y Visual Basic.",
        "choco-dart" | "pkg-dart" => "Lenguaje tipado de Google para aplicaciones multiplataforma y Flutter.",
        "choco-kotlin" | "pkg-kotlin" => "Lenguaje moderno interoperable con Java para JVM, Android y multiplataforma.",
        "pkg-scala" | "choco-scala" => "Lenguaje para la JVM que combina programación orientada a objetos y funcional.",
        "pkg-nim" | "choco-nim" => "Lenguaje compilado eficiente con sintaxis expresiva y generación de C/C++.",
        "pkg-crystal" => "Lenguaje compilado con sintaxis similar a Ruby y rendimiento nativo.",
        "pkg-gfortran" => "Compilador GNU de Fortran para cálculo científico y código numérico existente.",
        "pkg-erlang" | "winget-erlang" => "Runtime y lenguaje para sistemas distribuidos, concurrentes y tolerantes a fallos.",
        "pkg-elixir" | "choco-elixir" => "Lenguaje funcional sobre la máquina virtual de Erlang para servicios concurrentes.",
        "pkg-elixir-otp" => "Bibliotecas criptográficas y certificados TLS que Elixir necesita para Hex y HTTPS.",
        "pkg-ocaml" => "Lenguaje funcional con tipos estáticos, inferencia y compilación nativa.",
        "windows-msys2-ocaml" => "Toolchain OCaml para compilar y ejecutar programas funcionales nativos en Windows.",
        "pkg-clojure" => "Lisp funcional e inmutable para la JVM y sistemas de datos concurrentes.",
        "pkg-haskell" => "Lenguaje funcional puro con tipos avanzados y entorno interactivo GHCi.",
        "windows-ghcup" => "Gestor oficial de toolchains Haskell con GHC, Cabal y el servidor de lenguaje.",

        "pkg-gcc" | "windows-msys2-toolchain" => "Compiladores GCC de C, C++ y Fortran junto con depurador y herramientas de construcción.",
        "winget-llvm" | "pkg-clang" => "Toolchain LLVM con compiladores Clang de C y C++.",
        "winget-cmake" | "pkg-cmake" => "Genera proyectos y archivos de construcción portables para C, C++ y otros lenguajes.",
        "pkg-nasm" => "Ensamblador para arquitecturas x86 y x86-64 con sintaxis Intel.",
        "pkg-yasm" => "Ensamblador modular compatible con sintaxis NASM para x86.",
        "pkg-binutils" => "Ensamblador, enlazador y utilidades GNU para archivos binarios y objetos.",
        "winget-bazel" | "pkg-bazel" => "Sistema de construcción reproducible y escalable para repositorios multilenguaje.",
        "winget-ninja" | "pkg-ninja" => "Motor de construcción pequeño y rápido, normalmente generado por CMake o Meson.",
        "winget-meson" | "pkg-meson" => "Sistema de construcción moderno que genera proyectos Ninja.",
        "pkg-clang-tidy" => "Analizador estático y modernizador de código C y C++ basado en Clang.",
        "pkg-gdb" => "Depurador GNU para inspeccionar procesos, memoria, hilos y volcados.",
        "pkg-lldb" => "Depurador del proyecto LLVM para C, C++, Rust y otros binarios nativos.",
        "pkg-valgrind" => "Detecta fugas, accesos inválidos y problemas de rendimiento en programas nativos.",
        "choco-maven" | "pkg-maven" => "Construye y gestiona dependencias de proyectos Java mediante POM.",
        "choco-gradle" | "pkg-gradle" => "Sistema de construcción programable para JVM, Android y proyectos multilenguaje.",
        "choco-ant" | "pkg-ant" => "Herramienta de construcción Java basada en tareas declaradas en XML.",
        "pkg-sbt" => "Herramienta de construcción interactiva para Scala y proyectos JVM.",
        "winget-groovy" => "Lenguaje dinámico para la JVM usado en scripting y automatización de builds.",

        "winget-sqlite" | "pkg-sqlite" => "Base de datos SQL embebida, autocontenida y almacenada en un solo archivo.",
        "winget-mariadb" | "pkg-mariadb" => "Servidor y cliente SQL compatible con MySQL, con motor transaccional InnoDB.",
        "winget-mysql" | "pkg-mysql" => "Servidor y cliente de base de datos relacional MySQL.",
        "winget-postgresql" | "pkg-postgresql" => "Base de datos relacional avanzada y su cliente de consola psql.",
        "pkg-duckdb" => "Base analítica embebida optimizada para consultas columnares locales.",
        "winget-mongosh" | "pkg-mongosh" => "Shell oficial para consultar y administrar bases de datos MongoDB.",
        "winget-redis-cli" | "pkg-redis-cli" => "Cliente de consola para inspeccionar y administrar servidores Redis.",

        "winget-openvpn" | "pkg-openvpn" => "Cliente VPN basado en TLS para redes privadas y acceso remoto.",
        "winget-wireguard" | "pkg-wireguard" => "VPN moderna y ligera basada en pares de claves.",
        "winget-tailscale" | "pkg-tailscale" => "Red privada mallada basada en WireGuard con descubrimiento automático.",
        "winget-kubectl" | "pkg-kubectl" => "Cliente oficial para desplegar, consultar y administrar clústeres Kubernetes.",
        "winget-helm" | "pkg-helm" => "Gestor de paquetes de Kubernetes basado en charts reutilizables.",
        "winget-k9s" | "pkg-k9s" => "Interfaz de terminal para observar y administrar recursos de Kubernetes.",
        "winget-minikube" => "Crea un clúster Kubernetes local para desarrollo y aprendizaje.",
        "winget-kind" => "Ejecuta clústeres Kubernetes locales usando nodos dentro de contenedores.",
        "winget-kustomize" => "Personaliza manifiestos Kubernetes mediante capas y parches sin plantillas.",
        "winget-docker" | "pkg-docker" => "Construye, ejecuta y administra aplicaciones en contenedores.",
        "docker" | "docker-list" | "docker-start-linux" | "docker-start-win" | "docker-start-mac" => "Comprueba y administra el motor, contenedores e imágenes de Docker.",
        "winget-podman" | "pkg-podman" => "Motor de contenedores compatible con OCI, sin daemon obligatorio y con pods.",
        "winget-qemu" | "compat-qemu" => "Emula y virtualiza máquinas y arquitecturas completas.",
        "winget-virtualbox" | "compat-virtualbox" => "Hipervisor de escritorio para ejecutar máquinas virtuales completas.",
        "windows-hyperv-enable" | "windows-hyperv" => "Hipervisor integrado de Windows para máquinas virtuales y redes aisladas.",
        "windows-vmp-enable" => "Componente de virtualización que habilita WSL2 y otros hipervisores de Windows.",
        "windows-sandbox-enable" => "Entorno de Windows desechable y aislado para probar aplicaciones con seguridad.",
        "wsl-install-base" => "Ejecuta distribuciones Linux y sus herramientas directamente dentro de Windows.",

        "viewer-image" | "viewer-image-linux" => "Visor de imágenes y gráficos habituales, incluido SVG.",
        "viewer-media" | "viewer-media-linux" => "Reproductor multimedia para audio, vídeo y emisiones de red.",
        "viewer-document" | "viewer-document-linux" => "Visor ligero de PDF, libros electrónicos y documentos de solo lectura.",
        "viewer-archive" | "viewer-archive-linux" => "Comprime y extrae archivos en formatos habituales.",
        "viewer-files-dolphin" => "Gestor de archivos gráfico con pestañas, panel dividido y acceso remoto.",
        "viewer-code-oss" | "viewer-code" => "Editor de código extensible con depuración, terminal y control de versiones.",
        "editor-vscodium" => "Distribución comunitaria de VS Code sin telemetría ni marca de Microsoft.",
        "editor-vscodium-win" => "Distribución comunitaria de VS Code sin telemetría ni marca de Microsoft.",
        "editor-zed" => "Editor de código rápido con colaboración y herramientas asistidas.",
        "editor-zed-win" => "Editor de código rápido con colaboración y herramientas asistidas.",
        "editor-kate" => "Editor avanzado de KDE con proyectos, terminal y complementos de desarrollo.",
        "editor-neovim" => "Editor modal extensible y automatizable, compatible con el ecosistema Vim.",
        "editor-geany" => "Editor e IDE ligero con compilación, navegación y soporte multilenguaje.",
        "editor-emacs" => "Editor programable y entorno de trabajo extensible para código y texto.",
        "editor-helix" => "Editor modal moderno con selección múltiple y soporte LSP integrado.",
        "editor-micro" => "Editor de terminal accesible con atajos familiares, ratón y complementos.",
        "editor-notepadpp-win" => "Editor de texto ligero para Windows con pestañas, macros y resaltado de código.",
        "editor-sublime-win" => "Editor de código rápido con selección múltiple, comandos y amplia extensibilidad.",
        "editor-cursor-win" => "Editor basado en VS Code con funciones integradas de asistencia por IA.",
        "editor-antigravity-win" => "Editor de desarrollo asistido que integra agentes y automatización de código.",
        "editor-visualstudio-win" => "IDE completo para .NET, C++, depuración, pruebas y aplicaciones Windows.",
        "editor-jetbrains-toolbox-win" => "Administrador de instalación y actualización de los IDE de JetBrains.",
        "pkg-wine" | "wine" => "Capa de compatibilidad para ejecutar aplicaciones y comandos de Windows en Linux.",
        "pkg-winetricks" => "Instala runtimes, fuentes y componentes que algunas aplicaciones necesitan dentro de Wine.",
        "pkg-adb" | "adb" | "adb-install" | "adb-authorize" => "Conecta, depura, transfiere archivos y ejecuta comandos en dispositivos Android.",
        "pkg-ssh" | "ssh" | "winget-ssh" => "Cliente seguro para sesiones remotas, túneles y transferencia de archivos.",

        id if id.starts_with("framework-") => return framework_description(id),
        _ => return None,
    };
    Some(description)
}

fn framework_description(id: &str) -> Option<&'static str> {
    let description = match id {
        "framework-django" => "Framework web completo con ORM, administración, rutas y plantillas.",
        "framework-flask" | "framework-bottle" => "Microframework web ligero para servicios y aplicaciones pequeñas.",
        "framework-fastapi" => "Framework asíncrono para APIs tipadas con documentación OpenAPI automática.",
        "framework-starlette" | "framework-aiohttp" | "framework-sanic" | "framework-tornado" => "Base asíncrona para servicios web, WebSockets y tareas concurrentes.",
        "framework-pyramid" | "framework-falcon" | "framework-litestar" => "Framework para construir aplicaciones web y APIs con arquitectura flexible.",
        "framework-django-rest" | "framework-django-ninja" => "Herramientas para crear APIs sobre proyectos Django.",
        "framework-wagtail" => "CMS para Django orientado a contenido editorial y sitios administrables.",
        "framework-uvicorn" | "framework-gunicorn" => "Servidor de aplicaciones Python para publicar servicios web.",
        "framework-sqlalchemy" => "Toolkit SQL y ORM para mapear modelos Python a bases relacionales.",
        "framework-alembic" => "Gestiona migraciones versionadas de esquemas usados con SQLAlchemy.",
        "framework-sqlmodel" => "Modelos tipados que combinan Pydantic y SQLAlchemy.",
        "framework-tortoise" => "ORM asíncrono inspirado en Django para aplicaciones Python.",
        "framework-psycopg" | "framework-asyncpg" => "Controlador PostgreSQL para aplicaciones Python.",
        "framework-redis-py" => "Cliente Python para Redis, cachés, colas y estructuras en memoria.",
        "framework-pydantic" => "Valida, convierte y serializa datos usando anotaciones de tipos Python.",
        "framework-marshmallow" => "Define esquemas de validación y serialización de datos Python.",
        "framework-celery" => "Cola distribuida de tareas para trabajo asíncrono y programado.",
        "framework-requests" | "framework-httpx" => "Cliente HTTP para consumir APIs y servicios web desde Python.",
        "framework-scrapy" => "Framework para rastreo web y extracción estructurada de datos.",
        "framework-jinja" => "Motor de plantillas para generar HTML, texto y archivos de configuración.",
        "framework-numpy" => "Matrices multidimensionales y cálculo numérico vectorizado en Python.",
        "framework-scipy" => "Algoritmos científicos para optimización, señales, álgebra e integración.",
        "framework-pandas" => "Análisis y transformación de datos tabulares con DataFrame.",
        "framework-polars" => "DataFrames columnares rápidos con ejecución paralela y consultas diferidas.",
        "framework-matplotlib" | "framework-seaborn" => "Visualización estadística y gráficos para datos científicos.",
        "framework-torch" | "framework-tensorflow" => "Plataforma de aprendizaje automático y redes neuronales.",
        "framework-opencv" => "Procesamiento de imágenes, vídeo y visión por computador.",
        "framework-pillow" => "Lectura, conversión y manipulación de imágenes desde Python.",
        "framework-pyspark" => "Procesamiento distribuido de grandes conjuntos de datos con Apache Spark.",
        "framework-jupyter" => "Cuadernos interactivos para código, resultados, datos y documentación.",
        "framework-streamlit" | "framework-gradio" => "Crea interfaces web interactivas para datos y modelos desde Python.",
        "framework-boto3" => "SDK de Python para automatizar servicios de Amazon Web Services.",
        "framework-ansible" => "Automatiza configuración, despliegues y administración remota sin agentes.",
        "framework-prefect" => "Orquesta flujos de datos con planificación, reintentos y observabilidad.",
        "framework-mlflow" => "Registra experimentos, modelos y artefactos de aprendizaje automático.",
        "framework-poetry" | "framework-pipenv" => "Gestiona dependencias y entornos reproducibles de proyectos Python.",
        "framework-pytest" | "framework-pytest-asyncio" => "Ejecuta pruebas Python con fixtures y soporte para código asíncrono.",
        "framework-hypothesis" => "Genera casos de prueba automáticamente a partir de propiedades e invariantes.",
        "framework-robot" => "Automatización de pruebas y procesos mediante casos legibles por palabras clave.",
        "framework-coverage" => "Mide qué líneas y ramas de Python ejecutan las pruebas.",
        "framework-mypy" => "Comprueba tipos estáticos en código Python sin ejecutarlo.",
        "framework-ruff" => "Linter y formateador Python de alto rendimiento.",
        "framework-black" => "Formateador automático y determinista de código Python.",
        "framework-isort" => "Ordena y agrupa automáticamente las importaciones de Python.",
        "framework-tox" | "framework-nox" => "Automatiza pruebas en múltiples entornos y versiones de Python.",
        "framework-pre-commit" => "Ejecuta comprobaciones automáticas antes de crear commits.",
        "framework-invoke" => "Define y ejecuta tareas de automatización en Python.",
        "framework-click" | "framework-typer" => "Crea aplicaciones de línea de comandos en Python.",
        "framework-locust" => "Pruebas de carga programables para servicios y sitios web.",
        "framework-sphinx" | "framework-mkdocs" => "Genera documentación navegable desde texto y código fuente.",

        "framework-vite" | "framework-parcel" | "framework-esbuild" => "Servidor de desarrollo y empaquetador rápido para aplicaciones web.",
        "framework-webpack" | "framework-rollup" => "Empaqueta módulos y recursos para aplicaciones JavaScript.",
        "framework-swc" | "framework-babel" => "Transforma JavaScript y TypeScript para distintos entornos de ejecución.",
        "framework-tsx" => "Ejecuta TypeScript y ESM directamente durante el desarrollo.",
        "framework-next" | "framework-nuxt" | "framework-remix" | "framework-solid" | "framework-qwik" | "framework-redwood" => "Framework web de pila completa con renderizado de servidor y enrutado.",
        "framework-angular" | "framework-vue" | "framework-svelte" | "framework-react" | "framework-preact" => "Herramientas para crear interfaces web basadas en componentes.",
        "framework-astro" => "Framework web orientado a contenido que envía poco JavaScript al navegador.",
        "framework-nest" => "Framework estructurado para servicios Node.js escalables y tipados.",
        "framework-express" | "framework-koa" | "framework-fastify" | "framework-hono" | "framework-sails" => "Framework HTTP para APIs y aplicaciones de servidor en JavaScript.",
        "framework-electron" => "Crea aplicaciones de escritorio con tecnologías web y Node.js.",
        "framework-playwright" | "framework-cypress" => "Automatiza navegadores para pruebas funcionales de extremo a extremo.",
        "framework-jest" | "framework-vitest" | "framework-mocha" | "framework-ava" | "framework-ts-jest" => "Ejecuta pruebas automatizadas para JavaScript y TypeScript.",
        "framework-eslint" => "Detecta errores y aplica reglas de calidad en JavaScript y TypeScript.",
        "framework-prettier" => "Formatea código de forma consistente en múltiples lenguajes web.",
        "framework-storybook" => "Desarrolla y documenta componentes de interfaz de forma aislada.",
        "framework-prisma" | "framework-drizzle" | "framework-typeorm" | "framework-sequelize" => "Modela y consulta bases de datos desde aplicaciones JavaScript y TypeScript.",
        "framework-trpc" => "Crea APIs con tipos compartidos de extremo a extremo sin generar esquemas.",
        "framework-zod" => "Valida datos en tiempo de ejecución con esquemas inferibles por TypeScript.",
        "framework-msw" => "Intercepta peticiones de red para simular APIs en pruebas y desarrollo.",
        "framework-supertest" => "Prueba APIs HTTP de Node.js mediante aserciones sobre solicitudes y respuestas.",
        "framework-c8" => "Mide cobertura de código JavaScript usando el motor V8.",
        "framework-pnpm" | "framework-yarn" => "Gestor alternativo de dependencias para proyectos JavaScript.",
        "framework-turbo" | "framework-nx" | "framework-lerna" => "Coordina builds, tareas y caché en monorepos.",
        "framework-changesets" => "Gestiona versiones y notas de publicación en repositorios con varios paquetes.",
        "framework-serverless" => "Despliega funciones y servicios sin servidor en proveedores cloud.",
        "framework-vercel" | "framework-netlify" => "Despliega y administra proyectos web desde la terminal.",
        "framework-firebase" => "Administra proyectos, emuladores y despliegues de Firebase.",
        "framework-aws-cdk" => "Define infraestructura de AWS mediante código y construcciones reutilizables.",
        "framework-tsup" | "framework-unbuild" => "Empaqueta bibliotecas TypeScript para distintos formatos de módulo.",
        "framework-gulp" | "framework-grunt" => "Automatiza tareas de frontend mediante plugins y canalizaciones.",
        "framework-husky" | "framework-lint-staged" => "Ejecuta comprobaciones de calidad sobre commits y archivos preparados.",
        "framework-commitlint" => "Valida el formato y la convención de mensajes de commit.",
        "framework-semantic-release" | "framework-release-it" => "Automatiza versiones, changelog y publicación de releases.",
        "framework-typedoc" => "Genera documentación API a partir de tipos y comentarios TypeScript.",
        "framework-purescript" => "Lenguaje funcional fuertemente tipado que compila a JavaScript.",
        "framework-spago" | "framework-pulp" => "Construye y gestiona proyectos del ecosistema PureScript.",
        "framework-elm" => "Lenguaje funcional para interfaces web fiables sin excepciones en ejecución.",
        "framework-elm-test" => "Ejecuta pruebas de aplicaciones y paquetes Elm.",
        "framework-elm-format" => "Formatea código Elm de manera canónica.",

        "framework-cargo-leptos" => "Construye aplicaciones web Leptos de Rust con renderizado cliente y servidor.",
        "framework-wasm-pack" | "framework-trunk" => "Prepara y empaqueta aplicaciones Rust para WebAssembly.",
        "framework-cargo-watch" => "Reejecuta comandos Cargo al detectar cambios en el proyecto.",
        "framework-cargo-nextest" => "Ejecutor de pruebas Rust rápido, aislado y con informes detallados.",
        "framework-sqlx-cli" | "framework-diesel-cli" => "Gestiona esquemas y migraciones de bases de datos en proyectos Rust.",
        "framework-mdbook" => "Genera libros y documentación web desde Markdown.",
        "framework-cargo-generate" => "Crea proyectos Rust desde plantillas reutilizables.",
        "framework-cargo-audit" => "Busca vulnerabilidades conocidas en dependencias Rust.",
        "framework-cargo-deny" => "Aplica políticas de licencias, fuentes, duplicados y vulnerabilidades a dependencias Rust.",
        "framework-cargo-edit" => "Añade, elimina y actualiza dependencias Cargo desde la terminal.",
        "framework-cargo-expand" => "Muestra el código Rust resultante después de expandir macros.",
        "framework-cargo-make" => "Define flujos de tareas y automatización para proyectos Rust.",
        "framework-cargo-release" => "Automatiza versionado, etiquetas y publicación de crates.",
        "framework-cargo-tarpaulin" => "Mide cobertura de pruebas en proyectos Rust.",
        "framework-cargo-fuzz" => "Ejecuta fuzzing guiado por cobertura sobre código Rust.",
        "framework-cargo-binstall" => "Instala binarios Rust precompilados cuando están disponibles.",
        "framework-cargo-udeps" => "Detecta dependencias declaradas pero no utilizadas en proyectos Rust.",

        "framework-air" => "Recarga automáticamente aplicaciones Go cuando cambia el código.",
        "framework-golangci-lint" => "Ejecuta un conjunto configurable de analizadores estáticos para Go.",
        "framework-goreleaser" => "Automatiza builds, paquetes y releases multiplataforma de proyectos Go.",
        "framework-gopls" => "Servidor oficial del lenguaje Go para editores e IDE.",
        "framework-goose" | "framework-golang-migrate" => "Aplica y revierte migraciones de bases de datos desde proyectos Go.",
        "framework-sqlc" => "Genera código Go tipado a partir de consultas SQL.",
        "framework-swag" => "Genera documentación OpenAPI desde anotaciones de código Go.",
        "framework-gofumpt" | "framework-goimports" => "Formatea código Go y organiza sus importaciones.",
        "framework-staticcheck" => "Analizador estático avanzado para errores y malas prácticas en Go.",
        "framework-delve" => "Depurador específico para programas Go.",
        "framework-mockgen" => "Genera dobles de prueba para interfaces Go.",
        "framework-oapi-codegen" => "Genera clientes y servidores Go a partir de contratos OpenAPI.",
        "framework-templ" => "Sistema de componentes HTML tipados para Go.",
        "framework-ginkgo" => "Framework BDD para organizar y ejecutar pruebas Go.",

        "framework-laravel" | "framework-cakephp" | "framework-codeigniter" => "Framework web PHP de pila completa con estructura, rutas y persistencia.",
        "framework-symfony" => "Componentes reutilizables y consola para aplicaciones PHP.",
        "framework-phpunit" | "framework-pest" => "Framework de pruebas automatizadas para código PHP.",
        "framework-phpstan" | "framework-psalm" => "Análisis estático para detectar errores de tipos y flujo en PHP.",
        "framework-php-cs-fixer" | "framework-php-codesniffer" => "Comprueba y corrige convenciones de estilo en código PHP.",
        "framework-drush" => "Consola de administración, caché y despliegue para sitios Drupal.",
        "framework-livewire" => "Crea interfaces reactivas en Laravel usando principalmente PHP.",
        "framework-doctrine" => "ORM y capa de persistencia para aplicaciones PHP.",
        "framework-guzzle" => "Cliente HTTP para consumir servicios web desde PHP.",

        "framework-rails" | "framework-hanami" => "Framework web Ruby de pila completa.",
        "framework-sinatra" => "DSL minimalista para servicios y aplicaciones web Ruby.",
        "framework-rspec" | "framework-minitest" => "Framework de pruebas para aplicaciones Ruby.",
        "framework-rubocop" => "Linter y formateador basado en la guía de estilo de Ruby.",
        "framework-jekyll" => "Generador de sitios estáticos basado en Markdown y plantillas.",
        "framework-bundler" => "Resuelve y fija dependencias de proyectos Ruby.",
        "framework-sidekiq" => "Procesa trabajos en segundo plano para Ruby usando Redis.",
        "framework-puma" => "Servidor web concurrente para aplicaciones Ruby y Rack.",
        "framework-rake" => "Define y ejecuta tareas de automatización para proyectos Ruby.",

        "framework-dotnet-ef" => "Gestiona migraciones y modelos de Entity Framework Core.",
        "framework-aspnet-codegenerator" => "Genera controladores, vistas e identidad para proyectos ASP.NET.",
        "framework-csharpier" => "Formateador automático y determinista de código C#.",
        "framework-nswag" => "Genera contratos, clientes y servidores .NET desde OpenAPI.",
        "framework-paket" => "Gestor de dependencias para proyectos .NET y Mono.",
        "framework-phoenix" => "Framework web Elixir para aplicaciones concurrentes y en tiempo real.",
        "framework-credo" => "Analiza estilo, complejidad y calidad de código Elixir.",
        "framework-ex-doc" => "Genera documentación para proyectos Elixir y Erlang.",
        "framework-nerves" => "Plataforma Elixir para firmware y dispositivos embebidos.",
        "framework-dart-melos" => "Coordina paquetes y tareas en monorepos Dart y Flutter.",
        "framework-dart-mason" => "Genera archivos y estructuras de proyecto desde plantillas.",
        "framework-dart-very-good" => "Crea y mantiene proyectos Dart y Flutter con convenciones reproducibles.",
        "framework-dart-pana" => "Analiza la calidad, documentación y compatibilidad de paquetes Dart.",
        "framework-luarocks-busted" => "Framework de pruebas para Lua.",
        "framework-luarocks-luacheck" => "Analizador estático y linter para Lua.",
        "framework-luarocks-penlight" => "Biblioteca de utilidades generales para Lua.",
        "framework-luarocks-lpeg" => "Biblioteca de patrones de análisis basados en gramáticas para Lua.",
        "framework-conan" => "Gestor de paquetes y dependencias para C y C++.",
        "framework-meson" => "Sistema de construcción moderno para proyectos nativos.",
        "framework-platformio" => "Ecosistema de compilación, placas y bibliotecas para desarrollo embebido.",
        "framework-cppcheck" => "Analizador estático de errores y comportamiento indefinido en C y C++.",
        "framework-clang-format" => "Formateador configurable para C, C++ y lenguajes relacionados.",
        "framework-cabal-hlint" => "Sugiere simplificaciones y mejoras de estilo para código Haskell.",
        "framework-cabal-ormolu" | "framework-cabal-fourmolu" => "Formateador automático de código Haskell.",
        "framework-cabal-hls" => "Servidor de lenguaje Haskell para editores e IDE.",
        _ => return None,
    };
    Some(description)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn los_ciclos_comparten_descripcion() {
        assert_eq!(
            action_description("framework-django-uninstall"),
            action_description("framework-django")
        );
        assert_eq!(
            action_description("winget-ripgrep-version"),
            action_description("winget-ripgrep")
        );
    }
}
